
[datasets.drug_interaction_test]
name = "drug_interaction_test"
uuid = "672fad70-68ef-4278-b6ef-b1da2e09b57b"
description = "The testing data for the AllenAI drug interaction data set"
path = "./data/final_test_set.jsonl"

[datasets.drug_interaction_train]
name = "drug_interaction_train"
uuid = "df43677a-c5ef-4e8f-9aa3-7a5fcd095513"
description = "The training data for the AllenAI drug interaction data set"
path = "./data/final_train_set.jsonl"
